Audit changes
burnt-labs/burnt-cw-std pull request #24
Opened 2023-08-29 16:14 UTC by Peartes

These commits adds in the following changes

- Remove unused errors 
- Gracefully handle allowable is_allowed error
- Add events to the execute and instantiate calls
- Add in tests for events
- Properly validate sent funds in buy_item
- Add in event test
- Remove duplicate code logic

2023-08-29 16:55 UTC, Peartes commented on allowable/src/lib.rs
> +            Some(true) => Ok(self.allowed_addrs.has(deps.storage, addr)),
Here we gracefully handle the case where the allowable module isn't instantiated and hence

2023-08-29 16:56 UTC, Peartes commented on sales/src/execute.rs
> +                    if info.funds[0].amount.lt(&sale.price[0].amount) {
We made an error comparing the sent funds with itself instead of with the sale price

2023-08-29 16:59 UTC, Peartes commented on sellable/src/sellable_module.rs
> +use std::{cell::RefCell, rc::Rc};
This trait is to remove the duplication in code.
It creates a trait of similar functions both the Sellable and RSellable structs impl

2023-09-20 15:40 UTC, ash-burnt requested changes

2023-09-20 15:40 UTC, ash-burnt commented on allowable/src/test.rs
> +        let _info = mock_info(CREATOR, &[]);
Seems like this just gets redefined later on?

2023-09-20 15:40 UTC, ash-burnt commented on allowable/src/test.rs
> +        let _info = mock_info(CREATOR, &[]);
same here, this seems like a duplicate variable

2023-09-20 15:40 UTC, ash-burnt commented on allowable/src/lib.rs
> +        match self.enabled.may_load(deps.storage).unwrap() {
Let's avoid unwraps. Prefer `?`, it will bubble the appropriate error up

2023-09-20 15:40 UTC, ash-burnt commented on metadata/src/lib.rs
> +                    ("metadata", serde_json::to_string(&msg.metadata).unwrap()),
There are tons of unwraps in here, the whole repo could probably take a pass to get rid of them

2023-09-20 15:41 UTC, ash-burnt commented on metadata/src/lib.rs
> +                    ("metadata", serde_json::to_string(&msg.metadata).unwrap()),
In general, if the code is a function that returns a Result, you should not unwrap. In tests it is fine, but in code where we want to know how or why things went wrong, unwrap loses that info

2023-09-20 15:41 UTC, ash-burnt commented
This needs to have the formatter run, it doesn't pass linting

2026-08-08 14:22 UTC, closed without merging